// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_logs.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateAccessLog = `-- name: CreateAccessLog :one
INSERT INTO access_logs (
    user_id,
    api_token_id,
    resource_type,
    resource_id,
    action,
    ip_address,
    user_agent,
    success,
    error_message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, api_token_id, resource_type, resource_id, action, created_at, ip_address, user_agent, success, error_message
`

type CreateAccessLogParams struct {
	UserID       pgtype.UUID  `json:"user_id"`
	ApiTokenID   pgtype.UUID  `json:"api_token_id"`
	ResourceType string       `json:"resource_type"`
	ResourceID   uuid.UUID    `json:"resource_id"`
	Action       AccessAction `json:"action"`
	IpAddress    *netip.Addr  `json:"ip_address"`
	UserAgent    *string      `json:"user_agent"`
	Success      bool         `json:"success"`
	ErrorMessage *string      `json:"error_message"`
}

func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (AccessLog, error) {
	row := q.db.QueryRow(ctx, CreateAccessLog,
		arg.UserID,
		arg.ApiTokenID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.ErrorMessage,
	)
	var i AccessLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiTokenID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.CreatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const ListAccessLogsByResource = `-- name: ListAccessLogsByResource :many
SELECT id, user_id, api_token_id, resource_type, resource_id, action, created_at, ip_address, user_agent, success, error_message FROM access_logs
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAccessLogsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListAccessLogsByResource(ctx context.Context, arg ListAccessLogsByResourceParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, ListAccessLogsByResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiTokenID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.CreatedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAccessLogsByUser = `-- name: ListAccessLogsByUser :many
SELECT id, user_id, api_token_id, resource_type, resource_id, action, created_at, ip_address, user_agent, success, error_message FROM access_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccessLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAccessLogsByUser(ctx context.Context, arg ListAccessLogsByUserParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, ListAccessLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiTokenID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.CreatedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFailedAccessLogs = `-- name: ListFailedAccessLogs :many
SELECT id, user_id, api_token_id, resource_type, resource_id, action, created_at, ip_address, user_agent, success, error_message FROM access_logs
WHERE success = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFailedAccessLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFailedAccessLogs(ctx context.Context, arg ListFailedAccessLogsParams) ([]AccessLog, error) {
	rows, err := q.db.Query(ctx, ListFailedAccessLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessLog{}
	for rows.Next() {
		var i AccessLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiTokenID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.CreatedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
