// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (
    user_id,
    name,
    token_hash,
    scopes,
    organization_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, name, token_hash, scopes, organization_id, expires_at, last_used_at, usage_count, created_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	TokenHash      string             `json:"token_hash"`
	Scopes         []string           `json:"scopes"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, CreateAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.OrganizationID,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UsageCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const GetAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, scopes, organization_id, expires_at, last_used_at, usage_count, created_at, revoked_at FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, GetAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UsageCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const ListUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, user_id, name, token_hash, scopes, organization_id, expires_at, last_used_at, usage_count, created_at, revoked_at FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, ListUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.OrganizationID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.UsageCount,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, RevokeAPIToken, id)
	return err
}

const UpdateTokenUsage = `-- name: UpdateTokenUsage :exec
UPDATE api_tokens
SET 
    last_used_at = NOW(),
    usage_count = usage_count + 1
WHERE id = $1
`

func (q *Queries) UpdateTokenUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, UpdateTokenUsage, id)
	return err
}
