// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const CreateEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (
    project_id,
    name,
    description,
    is_protected,
    color
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, project_id, name, description, is_protected, color, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsProtected *bool     `json:"is_protected"`
	Color       *string   `json:"color"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, CreateEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.IsProtected,
		arg.Color,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsProtected,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments
WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteEnvironment, id)
	return err
}

const GetEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, project_id, name, description, is_protected, color, created_at, updated_at FROM environments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, GetEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsProtected,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT id, project_id, name, description, is_protected, color, created_at, updated_at FROM environments
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetEnvironmentByNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, GetEnvironmentByName, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsProtected,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, description, is_protected, color, created_at, updated_at FROM environments
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, ListEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.IsProtected,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments
SET 
    description = COALESCE($2, description),
    is_protected = COALESCE($3, is_protected),
    color = COALESCE($4, color),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, description, is_protected, color, created_at, updated_at
`

type UpdateEnvironmentParams struct {
	ID          uuid.UUID `json:"id"`
	Description *string   `json:"description"`
	IsProtected *bool     `json:"is_protected"`
	Color       *string   `json:"color"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, UpdateEnvironment,
		arg.ID,
		arg.Description,
		arg.IsProtected,
		arg.Color,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.IsProtected,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
