// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessAction string

const (
	AccessActionRead   AccessAction = "read"
	AccessActionCreate AccessAction = "create"
	AccessActionUpdate AccessAction = "update"
	AccessActionDelete AccessAction = "delete"
)

func (e *AccessAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessAction(s)
	case string:
		*e = AccessAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessAction: %T", src)
	}
	return nil
}

type NullAccessAction struct {
	AccessAction AccessAction `json:"access_action"`
	Valid        bool         `json:"valid"` // Valid is true if AccessAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessAction) Scan(value interface{}) error {
	if value == nil {
		ns.AccessAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessAction), nil
}

func (e AccessAction) Valid() bool {
	switch e {
	case AccessActionRead,
		AccessActionCreate,
		AccessActionUpdate,
		AccessActionDelete:
		return true
	}
	return false
}

func AllAccessActionValues() []AccessAction {
	return []AccessAction{
		AccessActionRead,
		AccessActionCreate,
		AccessActionUpdate,
		AccessActionDelete,
	}
}

type OrgRole string

const (
	OrgRoleOwner  OrgRole = "owner"
	OrgRoleAdmin  OrgRole = "admin"
	OrgRoleMember OrgRole = "member"
	OrgRoleViewer OrgRole = "viewer"
)

func (e *OrgRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgRole(s)
	case string:
		*e = OrgRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgRole: %T", src)
	}
	return nil
}

type NullOrgRole struct {
	OrgRole OrgRole `json:"org_role"`
	Valid   bool    `json:"valid"` // Valid is true if OrgRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrgRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgRole), nil
}

func (e OrgRole) Valid() bool {
	switch e {
	case OrgRoleOwner,
		OrgRoleAdmin,
		OrgRoleMember,
		OrgRoleViewer:
		return true
	}
	return false
}

func AllOrgRoleValues() []OrgRole {
	return []OrgRole{
		OrgRoleOwner,
		OrgRoleAdmin,
		OrgRoleMember,
		OrgRoleViewer,
	}
}

type SecretAction string

const (
	SecretActionCreated SecretAction = "created"
	SecretActionUpdated SecretAction = "updated"
	SecretActionDeleted SecretAction = "deleted"
	SecretActionRotated SecretAction = "rotated"
)

func (e *SecretAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecretAction(s)
	case string:
		*e = SecretAction(s)
	default:
		return fmt.Errorf("unsupported scan type for SecretAction: %T", src)
	}
	return nil
}

type NullSecretAction struct {
	SecretAction SecretAction `json:"secret_action"`
	Valid        bool         `json:"valid"` // Valid is true if SecretAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSecretAction) Scan(value interface{}) error {
	if value == nil {
		ns.SecretAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SecretAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSecretAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SecretAction), nil
}

func (e SecretAction) Valid() bool {
	switch e {
	case SecretActionCreated,
		SecretActionUpdated,
		SecretActionDeleted,
		SecretActionRotated:
		return true
	}
	return false
}

func AllSecretActionValues() []SecretAction {
	return []SecretAction{
		SecretActionCreated,
		SecretActionUpdated,
		SecretActionDeleted,
		SecretActionRotated,
	}
}

type AccessLog struct {
	ID           uuid.UUID    `json:"id"`
	UserID       pgtype.UUID  `json:"user_id"`
	ApiTokenID   pgtype.UUID  `json:"api_token_id"`
	ResourceType string       `json:"resource_type"`
	ResourceID   uuid.UUID    `json:"resource_id"`
	Action       AccessAction `json:"action"`
	CreatedAt    time.Time    `json:"created_at"`
	IpAddress    *netip.Addr  `json:"ip_address"`
	UserAgent    *string      `json:"user_agent"`
	Success      bool         `json:"success"`
	ErrorMessage *string      `json:"error_message"`
}

type ActiveSecretsByEnvironment struct {
	EnvironmentID   uuid.UUID `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	ProjectID       uuid.UUID `json:"project_id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	SecretCount     int64     `json:"secret_count"`
}

type ApiToken struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	TokenHash      string             `json:"token_hash"`
	Scopes         []string           `json:"scopes"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	UsageCount     *int32             `json:"usage_count"`
	CreatedAt      time.Time          `json:"created_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type Environment struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsProtected *bool     `json:"is_protected"`
	Color       *string   `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Organization struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	PlanType             *string            `json:"plan_type"`
	MaxProjects          *int32             `json:"max_projects"`
	MaxSecretsPerProject *int32             `json:"max_secrets_per_project"`
	OwnerID              uuid.UUID          `json:"owner_id"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type OrganizationMember struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           OrgRole            `json:"role"`
	InvitedBy      pgtype.UUID        `json:"invited_by"`
	InvitedAt      pgtype.Timestamptz `json:"invited_at"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type Project struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	EncryptedDek   string             `json:"encrypted_dek"`
	DekVersion     int32              `json:"dek_version"`
	Color          *string            `json:"color"`
	Icon           *string            `json:"icon"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Secret struct {
	ID                uuid.UUID          `json:"id"`
	EnvironmentID     uuid.UUID          `json:"environment_id"`
	Key               string             `json:"key"`
	EncryptedValue    string             `json:"encrypted_value"`
	Description       *string            `json:"description"`
	IsActive          *bool              `json:"is_active"`
	Version           int32              `json:"version"`
	PreviousVersionID pgtype.UUID        `json:"previous_version_id"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type SecretHistory struct {
	ID             uuid.UUID    `json:"id"`
	SecretID       uuid.UUID    `json:"secret_id"`
	EnvironmentID  uuid.UUID    `json:"environment_id"`
	Action         SecretAction `json:"action"`
	Key            string       `json:"key"`
	EncryptedValue *string      `json:"encrypted_value"`
	ChangedBy      uuid.UUID    `json:"changed_by"`
	CreatedAt      time.Time    `json:"created_at"`
	IpAddress      *netip.Addr  `json:"ip_address"`
	UserAgent      *string      `json:"user_agent"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	FullName       *string            `json:"full_name"`
	AvatarUrl      *string            `json:"avatar_url"`
	AuthProviderID *string            `json:"auth_provider_id"`
	IsActive       *bool              `json:"is_active"`
	EmailVerified  *bool              `json:"email_verified"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type UserAccessibleProject struct {
	ProjectID        uuid.UUID `json:"project_id"`
	ProjectName      string    `json:"project_name"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	UserID           uuid.UUID `json:"user_id"`
	UserRole         OrgRole   `json:"user_role"`
}
