// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const CreateOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name,
    slug,
    plan_type,
    max_projects,
    max_secrets_per_project,
    owner_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, slug, plan_type, max_projects, max_secrets_per_project, owner_id, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	Name                 string    `json:"name"`
	Slug                 string    `json:"slug"`
	PlanType             *string   `json:"plan_type"`
	MaxProjects          *int32    `json:"max_projects"`
	MaxSecretsPerProject *int32    `json:"max_secrets_per_project"`
	OwnerID              uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, CreateOrganization,
		arg.Name,
		arg.Slug,
		arg.PlanType,
		arg.MaxProjects,
		arg.MaxSecretsPerProject,
		arg.OwnerID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanType,
		&i.MaxProjects,
		&i.MaxSecretsPerProject,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, plan_type, max_projects, max_secrets_per_project, owner_id, created_at, updated_at, deleted_at FROM organizations
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, GetOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanType,
		&i.MaxProjects,
		&i.MaxSecretsPerProject,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, plan_type, max_projects, max_secrets_per_project, owner_id, created_at, updated_at, deleted_at FROM organizations
WHERE slug = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, GetOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanType,
		&i.MaxProjects,
		&i.MaxSecretsPerProject,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.name, o.slug, o.plan_type, o.max_projects, o.max_secrets_per_project, o.owner_id, o.created_at, o.updated_at, o.deleted_at FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1 AND o.deleted_at IS NULL
ORDER BY o.created_at DESC
`

func (q *Queries) ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, ListUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PlanType,
			&i.MaxProjects,
			&i.MaxSecretsPerProject,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteOrganization, id)
	return err
}

const UpdateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET 
    name = COALESCE($2, name),
    plan_type = COALESCE($3, plan_type),
    max_projects = COALESCE($4, max_projects),
    max_secrets_per_project = COALESCE($5, max_secrets_per_project),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, plan_type, max_projects, max_secrets_per_project, owner_id, created_at, updated_at, deleted_at
`

type UpdateOrganizationParams struct {
	ID                   uuid.UUID `json:"id"`
	Name                 string    `json:"name"`
	PlanType             *string   `json:"plan_type"`
	MaxProjects          *int32    `json:"max_projects"`
	MaxSecretsPerProject *int32    `json:"max_secrets_per_project"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, UpdateOrganization,
		arg.ID,
		arg.Name,
		arg.PlanType,
		arg.MaxProjects,
		arg.MaxSecretsPerProject,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanType,
		&i.MaxProjects,
		&i.MaxSecretsPerProject,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
