// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const CountProjectsByOrganization = `-- name: CountProjectsByOrganization :one
SELECT COUNT(*) FROM projects
WHERE organization_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountProjectsByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateProject = `-- name: CreateProject :one
INSERT INTO projects (
    organization_id,
    name,
    description,
    encrypted_dek,
    dek_version,
    color,
    icon
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, organization_id, name, description, encrypted_dek, dek_version, color, icon, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	EncryptedDek   string    `json:"encrypted_dek"`
	DekVersion     int32     `json:"dek_version"`
	Color          *string   `json:"color"`
	Icon           *string   `json:"icon"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, CreateProject,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.EncryptedDek,
		arg.DekVersion,
		arg.Color,
		arg.Icon,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.DekVersion,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, name, description, encrypted_dek, dek_version, color, icon, created_at, updated_at, deleted_at FROM projects
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, GetProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.DekVersion,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, name, description, encrypted_dek, dek_version, color, icon, created_at, updated_at, deleted_at FROM projects
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, ListProjectsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.EncryptedDek,
			&i.DekVersion,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RotateProjectDEK = `-- name: RotateProjectDEK :one
UPDATE projects
SET 
    encrypted_dek = $2,
    dek_version = dek_version + 1,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, name, description, encrypted_dek, dek_version, color, icon, created_at, updated_at, deleted_at
`

type RotateProjectDEKParams struct {
	ID           uuid.UUID `json:"id"`
	EncryptedDek string    `json:"encrypted_dek"`
}

func (q *Queries) RotateProjectDEK(ctx context.Context, arg RotateProjectDEKParams) (Project, error) {
	row := q.db.QueryRow(ctx, RotateProjectDEK, arg.ID, arg.EncryptedDek)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.DekVersion,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const SoftDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteProject, id)
	return err
}

const UpdateProject = `-- name: UpdateProject :one
UPDATE projects
SET 
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    color = COALESCE($4, color),
    icon = COALESCE($5, icon),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, name, description, encrypted_dek, dek_version, color, icon, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Color       *string   `json:"color"`
	Icon        *string   `json:"icon"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, UpdateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Icon,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.EncryptedDek,
		&i.DekVersion,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
