// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountSecretsByEnvironment(ctx context.Context, environmentID uuid.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (AccessLog, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateSecret(ctx context.Context, arg DeactivateSecretParams) error
	DeleteEnvironment(ctx context.Context, id uuid.UUID) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error)
	GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetSecretByID(ctx context.Context, id uuid.UUID) (Secret, error)
	GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (Secret, error)
	GetUserByAuthProviderID(ctx context.Context, authProviderID *string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAccessLogsByResource(ctx context.Context, arg ListAccessLogsByResourceParams) ([]AccessLog, error)
	ListAccessLogsByUser(ctx context.Context, arg ListAccessLogsByUserParams) ([]AccessLog, error)
	ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]Environment, error)
	ListFailedAccessLogs(ctx context.Context, arg ListFailedAccessLogsParams) ([]AccessLog, error)
	ListProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Project, error)
	ListSecretsByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Secret, error)
	ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]ApiToken, error)
	ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]Organization, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeAPIToken(ctx context.Context, id uuid.UUID) error
	RotateProjectDEK(ctx context.Context, arg RotateProjectDEKParams) (Project, error)
	SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
	UpdateTokenUsage(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
