// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CountSecretsByEnvironment = `-- name: CountSecretsByEnvironment :one
SELECT COUNT(*) FROM secrets
WHERE environment_id = $1 AND deleted_at IS NULL AND is_active = true
`

func (q *Queries) CountSecretsByEnvironment(ctx context.Context, environmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountSecretsByEnvironment, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateSecret = `-- name: CreateSecret :one
INSERT INTO secrets (
    environment_id,
    key,
    encrypted_value,
    description,
    is_active,
    version,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, environment_id, key, encrypted_value, description, is_active, version, previous_version_id, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateSecretParams struct {
	EnvironmentID  uuid.UUID   `json:"environment_id"`
	Key            string      `json:"key"`
	EncryptedValue string      `json:"encrypted_value"`
	Description    *string     `json:"description"`
	IsActive       *bool       `json:"is_active"`
	Version        int32       `json:"version"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, CreateSecret,
		arg.EnvironmentID,
		arg.Key,
		arg.EncryptedValue,
		arg.Description,
		arg.IsActive,
		arg.Version,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.IsActive,
		&i.Version,
		&i.PreviousVersionID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const DeactivateSecret = `-- name: DeactivateSecret :exec
UPDATE secrets
SET is_active = false, updated_by = $2
WHERE id = $1
`

type DeactivateSecretParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) DeactivateSecret(ctx context.Context, arg DeactivateSecretParams) error {
	_, err := q.db.Exec(ctx, DeactivateSecret, arg.ID, arg.UpdatedBy)
	return err
}

const GetSecretByID = `-- name: GetSecretByID :one
SELECT id, environment_id, key, encrypted_value, description, is_active, version, previous_version_id, created_by, updated_by, created_at, updated_at, deleted_at FROM secrets
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSecretByID(ctx context.Context, id uuid.UUID) (Secret, error) {
	row := q.db.QueryRow(ctx, GetSecretByID, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.IsActive,
		&i.Version,
		&i.PreviousVersionID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetSecretByKey = `-- name: GetSecretByKey :one
SELECT id, environment_id, key, encrypted_value, description, is_active, version, previous_version_id, created_by, updated_by, created_at, updated_at, deleted_at FROM secrets
WHERE environment_id = $1 AND key = $2 AND deleted_at IS NULL AND is_active = true
LIMIT 1
`

type GetSecretByKeyParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	Key           string    `json:"key"`
}

func (q *Queries) GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (Secret, error) {
	row := q.db.QueryRow(ctx, GetSecretByKey, arg.EnvironmentID, arg.Key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.IsActive,
		&i.Version,
		&i.PreviousVersionID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListSecretsByEnvironment = `-- name: ListSecretsByEnvironment :many
SELECT id, environment_id, key, encrypted_value, description, is_active, version, previous_version_id, created_by, updated_by, created_at, updated_at, deleted_at FROM secrets
WHERE environment_id = $1 AND deleted_at IS NULL AND is_active = true
ORDER BY key ASC
`

func (q *Queries) ListSecretsByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Secret, error) {
	rows, err := q.db.Query(ctx, ListSecretsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.EncryptedValue,
			&i.Description,
			&i.IsActive,
			&i.Version,
			&i.PreviousVersionID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteSecret = `-- name: SoftDeleteSecret :exec
UPDATE secrets
SET 
    deleted_at = NOW(),
    is_active = false,
    updated_by = $2
WHERE id = $1
`

type SoftDeleteSecretParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) error {
	_, err := q.db.Exec(ctx, SoftDeleteSecret, arg.ID, arg.UpdatedBy)
	return err
}

const UpdateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET 
    encrypted_value = $2,
    description = COALESCE($3, description),
    version = version + 1,
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, environment_id, key, encrypted_value, description, is_active, version, previous_version_id, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateSecretParams struct {
	ID             uuid.UUID   `json:"id"`
	EncryptedValue string      `json:"encrypted_value"`
	Description    *string     `json:"description"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, UpdateSecret,
		arg.ID,
		arg.EncryptedValue,
		arg.Description,
		arg.UpdatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.IsActive,
		&i.Version,
		&i.PreviousVersionID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
