// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    full_name,
    avatar_url,
    auth_provider_id,
    is_active,
    email_verified
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, full_name, avatar_url, auth_provider_id, is_active, email_verified, created_at, updated_at, last_login_at, deleted_at
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	FullName       *string `json:"full_name"`
	AvatarUrl      *string `json:"avatar_url"`
	AuthProviderID *string `json:"auth_provider_id"`
	IsActive       *bool   `json:"is_active"`
	EmailVerified  *bool   `json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.AuthProviderID,
		arg.IsActive,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.AuthProviderID,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByAuthProviderID = `-- name: GetUserByAuthProviderID :one
SELECT id, email, full_name, avatar_url, auth_provider_id, is_active, email_verified, created_at, updated_at, last_login_at, deleted_at FROM users
WHERE auth_provider_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByAuthProviderID(ctx context.Context, authProviderID *string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByAuthProviderID, authProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.AuthProviderID,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, avatar_url, auth_provider_id, is_active, email_verified, created_at, updated_at, last_login_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.AuthProviderID,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, avatar_url, auth_provider_id, is_active, email_verified, created_at, updated_at, last_login_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.AuthProviderID,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, email, full_name, avatar_url, auth_provider_id, is_active, email_verified, created_at, updated_at, last_login_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.AuthProviderID,
			&i.IsActive,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteUser, id)
	return err
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    full_name = COALESCE($2, full_name),
    avatar_url = COALESCE($3, avatar_url),
    is_active = COALESCE($4, is_active),
    email_verified = COALESCE($5, email_verified),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, full_name, avatar_url, auth_provider_id, is_active, email_verified, created_at, updated_at, last_login_at, deleted_at
`

type UpdateUserParams struct {
	ID            uuid.UUID `json:"id"`
	FullName      *string   `json:"full_name"`
	AvatarUrl     *string   `json:"avatar_url"`
	IsActive      *bool     `json:"is_active"`
	EmailVerified *bool     `json:"email_verified"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.ID,
		arg.FullName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.AuthProviderID,
		&i.IsActive,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const UpdateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, UpdateUserLastLogin, id)
	return err
}
